name: loopchain
type: app
adopt-info: loopchain
confinement: strict
base: core18

parts:
  install-dependency:
    plugin: python
    python-version: python3
    python-packages:
      - idna==2.7
    build-packages:
      - automake
      - pkg-config
      - libtool
      - curl
      - jq
      - tree
  loopchain:
    after: [ install-dependency ]
    plugin: python
    python-version: python3
    source-type: git
    source: https://github.com/icon-project/loopchain.git
    parse-info: [$SNAPCRAFT_PROJECT_DIR/snap/local/org.iconrepublic.loopchain.appdata.xml]
    override-pull: |
      snapcraftctl pull
      LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
      git checkout ${LATEST_TAG}
      pwd
      env
      cd /root/project
      ls -al
      # VERSION=$(python -c "import asset; print(asset.get_version())")
      # echo "curl https://api.github.com/repos/icon-project/icon-release/releases/latest"
      # curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/icon-project/icon-release/releases/latest
      # VERSION=$(curl -H "Accept:application/vnd.github.v3+json" \
      #  https://api.github.com/repos/icon-project/icon-release/releases/latest | jq -r .tag_name)
      # echo "release version : ${VERSION}"
      # snapcraftctl set-version ${VERSION}
      snapcraftctl set-grade stable
    override-build: |
      echo "loopchain build"
    stage-packages:
      - python-six
    stage:
      - -usr/bin/*
      - -usr/share/*python*

apps:
  loopchain:
    command: $SNAP/bin/loopchain
    common-id: org.iconrepublic.loopchain
    plugs:
      - home
      - network
      - network-bind
      - removable-media
