name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cr:
        description: 'container registry'
        required: true
        default: 'ghcr'
        type: choice
        options:
          - ghcr
          - ecr

env:
  REGISTRY: ghcr.io
  TERNARY_REGISTRY: ${{ (github.event_name == 'workflow_dispatch' && inputs.cr == 'ecr') && 'damoang' || 'ghcr.io' }}

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v5
      - name: print context
        run: |
          if [ "$CI" = "true" ]; then
            echo "This is a CI environment."
          else
            echo "This is not a CI environment."
          fi
          echo "inputs.cr = ${{ inputs.cr }}"
          echo "env.registry = ${{ env.REGISTRY }}"
          echo "env.ternary_registry = ${{ env.TERNARY_REGISTRY }}"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ inputs.cr }}" == "ecr" ]; then
            echo "change registry to ${{ inputs.cr }}"
            echo "REGISTRY=${{ inputs.cr }}" >> $GITHUB_ENV
          fi

          echo "github.event_name = ${{ github.event_name }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
      - name: Run for main
        run: |
          echo "env.registry = ${{ env.REGISTRY }}"
          echo "REGISTRY = $REGISTRY"
          echo "::notice::main"

  envs:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: print env
        run: |
          echo "env.registry = ${{ env.REGISTRY }}"
          echo "REGISTRY = $REGISTRY"
          echo "env.ternary_registry = ${{ env.TERNARY_REGISTRY }}"
      
      - name: Checkout
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Deploy
        env:
          ECR_REPOSITORY: 'damoang'
        run: |
          echo "deploy"
          uv run scripts/deploy.py
