name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:


jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: print context
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
      - name: Run for main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "::notice::main"
      - name: Run for develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "::notice::develop"