name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cr:
        description: 'container registry'
        required: true
        default: 'ghcr'
        type: choice
        options:
          - ghcr
          - ecr

env:
  REGISTRY: ${{ (github.event_name == 'workflow_dispath' && inputs.cr == 'ecr') && 'damoang' || 'ghcr.io' }}

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: print context
        run: |
          if [ "$CI" = "true" ]; then
            echo "This is a CI environment."
          else
            echo "This is not a CI environment."
          fi
          echo "env.registry = ${{ env.REGISTRY }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
      - name: Run for main
        run: |
          echo "::notice::main"
