name: Deploy

on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:

env:
  REGISTRY_TYPE: ''
  GHCR_IMAGE_NAME: 'ghcr.io/damoang/damoang-guide:latest'
  ECR_REPOSITORY: 'damoang'
  AWS_REGION: 'ap-northeast-2'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Deploy
        env:
          IMAGE_REF: ${{ github.event.client_payload.image_ref }}
          ECR_REPOSITORY: 'damoang'
        run: |
          echo "deploy"
          echo "artifacts_url = ${{ github.event.workflow_run.artifacts_url }}"
          echo "env.image_ref = ${{ env.IMAGE_REF }}"
          uv run scripts/deploy.py
