name: Deploy

on:
  repository_dispatch:
    types: [deploy-event]
  workflow_dispatch:

env:
  GHCR_IMAGE_NAME: 'ghcr.io/damoang/damoang-guide:latest'
  ECR_REPOSITORY: 'damoang'
  AWS_REGION: 'ap-northeast-2'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            scripts

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Deploy
        env:
          IMAGE_REF: ${{ github.event.client_payload.image_ref }}
          REGISTRY: ${{ github.event.client_payload.registry }}
          ECR_REPOSITORY: 'damoang'
        run: |
          ls -al
          echo "deploy"
          echo "artifacts_url = ${{ github.event.workflow_run.artifacts_url }}"
          echo "env.image_ref = ${{ env.IMAGE_REF }}"
          uv run scripts/deploy.py

      - name: Check AWS CLI version
        run: aws --version
